#!/usr/bin/env bash
#
# Run QuiteRSS in a Docker container.
# `set -e` останавливает выполнение script, если в команде или конвейере есть ошибка - что является противоположностью поведения оболочки по умолчанию, которое должно игнорировать ошибки в скриптах.
# Это не рекомендуемый метод, особенно в сценариях `init.d`.
set -e

readonly IMAGE_NAME='dzmuh/quiterss'
readonly CONTAINER_NAME='quiterss'

# Pull latest Docker image to have the latest version.
ip r|grep "default\|0.0.0.0" 1>/dev/null && docker pull "${IMAGE_NAME}"

readonly RUNNING_CONTAINER_ID=$(docker ps --quiet --filter "name=${CONTAINER_NAME}")
[[ "${RUNNING_CONTAINER_ID}" = "" ]] || exit

readonly USER_CONFIG_DIR="${HOME}/.config/QuiteRss"
if [[ ! -e "${USER_CONFIG_DIR}" ]]; then
    mkdir --parent "${USER_CONFIG_DIR}"
fi

readonly USER_DATA_DIR="${HOME}/.local/share/QuiteRss"
if [[ ! -e "${USER_DATA_DIR}" ]]; then
    mkdir --parent "${USER_DATA_DIR}"
fi

# http://patorjk.com/software/taag/#p=display&h=0&f=Calvin%20S&t=QuiteRSS
cat <<EOH

╔═╗ ┬ ┬┬┌┬┐┌─┐╦═╗╔═╗╔═╗
║═╬╗│ ││ │ ├┤ ╠╦╝╚═╗╚═╗
╚═╝╚└─┘┴ ┴ └─┘╩╚═╚═╝╚═╝
${IMAGE_NAME}

========
Volumes:
========
Config Dir..: '${USER_CONFIG_DIR}'
Data Dir....: '${USER_DATA_DIR}'

EOH

# removing previous existing containers to enable start up
docker rm --force --volumes "${CONTAINER_NAME}" >/dev/null 2>&1 || true

readonly CONTAINER_ID=$(docker run \
    --rm \
    -it \
    --name "${CONTAINER_NAME}" \
    --hostname ${CONTAINER_NAME} \
    --volume /etc/localtime:/etc/localtime:ro \
    ` # Audio` \
    --device /dev/snd \
    ` # Video` \
    --env DISPLAY \
    --volume /tmp/.X11-unix:/tmp/.X11-unix:ro \
    `# Entrypoint` \
    --env GIVEN_GROUP="$(id -gn "${USER}")" \
    --env GIVEN_GROUP_ID="$(id -g "${USER}")" \
    --env GIVEN_USER="${USER}" \
    --env GIVEN_USER_ID="${UID}" \
    `# QuiteRss` \
    --volume "${USER_CONFIG_DIR}":/volume/config \
    --volume "${USER_DATA_DIR}":/volume/data \
    "${IMAGE_NAME}" )
echo "${CONTAINER_ID}"
